import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Button from '../components/Button'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter()

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' select-none'>
        <h1 className='fixed left-8 top-6 text-3xl font-semibold'>
          G R I F F I N
        </h1>

        <div className='fixed right-8 top-6'>
          <Button
            label={'Launch App'}
            size="lg"
            onClickHandler={() => {
              // authentication

              // if autenticated, load dashboard
              router.push('/dashboard')
            }}
          />
        </div>

        <h1 className='fixed left-8 bottom-1/2 text-6xl font-thin'>
          Private Payroll Solusions <br />for Enterprises
        </h1>

        <h1 className='fixed left-8 bottom-8 text-md font-light'>
          Powered by Polygon Nightfall
        </h1>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div >
  )
}
